carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name = 'cart'),
    path('add-cart/<int:id>/', views.add_cart, name = 'add-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name = 'remove-cart'),
    path('remove-cart-item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name = 'remove-cart-item'),
    
    path('checkout/', views.checkout, name = 'checkout'), 
    path('calculate-coupon-discount/', views.calculate_coupon_discount, name='calculate_coupon_discount'),

]

sneaker_street/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('',include('userside.urls')),
    path('adminlogin/',include('adminside.urls')),
    path('',include('userprofile.urls')),
    path('cart/',include('carts.urls')),
    path('orders/',include('orders.urls')),
    path('wallet/', include('wallet.urls')),
     path('offers/', include('offers.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userprofile/urls.py
from django.urls import path
from . import views
app_name = 'userprofile'

urlpatterns = [
    
    path('user-profile/', views.user_profile, name="user-profile"),
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('change_Password/', views.change_password, name='change-password'),
    path('user-orders/', views.user_orders, name='user-orders'),
    path('user-address/', views.user_address, name='user-address'),
    path('edit-address/<int:address_id>/', views.edit_address, name='edit-address'),
    path('user-add-address/', views.user_add_address, name='user-add-address'),
    


 

]

wallet/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('wallet/', views.wallet, name='wallet'),
  path("getwallet_total", views.get_wallet_grand_total, name="get_wallet_grand_total"),

]

userprofile/models.py
from django.db import models
from userside.models import UserProfile
# Create your models here.
from django.db import models
from userside.models import UserProfile

class Userdetails(models.Model):

    userprofile =  models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=25, blank=True,default="")
    date_of_birth = models.DateField(blank=True, null=True)
    profile_image = models.ImageField(upload_to="photos/profile", blank=True, null=True,)

wallet/models.py
from django.db import models
from userside.models import UserProfile
from orders.models import Order
# Create your models here.


class Wallet(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    balance = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username + str(self.balance)
    


class WalletTransaction(models.Model):
    TRANSACTION_TYPE_CHOICES = (
        ("CREDIT", "Credit"),
        ("DEBIT", "Debit"),
    )

    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL)
    transaction_type = models.CharField(choices=TRANSACTION_TYPE_CHOICES, max_length=10)
    transaction_detail = models.CharField(max_length=50)
    amount = models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.transaction_type + str(self.wallet) + str(self.amount)

userprofile/views.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from orders.forms import addressbook_form
from userside.models import AddressBook
from userside.views import UserProfile
from .models import Userdetails
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from orders.models import OrderProduct, Order
from django.views.decorators.cache import cache_control
import re
from datetime import date


# Create your views here.
@login_required
@cache_control(no_cache=True,must_revalidate=True,no_store=True)
def user_profile(request):
    selected_menu = request.GET.get('menu_item' , 'profile')
    print(request)
    user_profile_instance = UserProfile.objects.get(email=request.user)
    
    userdetails, created = Userdetails.objects.get_or_create(userprofile=user_profile_instance)

    context = {
        'user': request.user,
        'userdetails': userdetails,
        'selected_menu': selected_menu,
        
    }
    return render(request, 'userprofile/account.html', context)



@login_required
@cache_control(no_cache=True,must_revalidate=True,no_store=True)
def edit_profile(request):
    user_profile_instance = UserProfile.objects.get(email=request.user)
    userdetails, created = Userdetails.objects.get_or_create(userprofile=user_profile_instance)

    if request.method == 'POST':
        fullname = request.POST['full_name'].strip()
        phone = request.POST['phone'].strip()
        date_of_birth = request.POST['DOB'].strip()
        
         # Custom validation logic
        name_pattern = r'^[A-Za-z. ]+$'
        phone_pattern = r'^\d{10}$'

        if len(fullname) <= 3:
            messages.error(request, "Full name must be longer than 3 characters.")
        elif not re.match(name_pattern, fullname):
            messages.error(request, "Invalid full name. Please use only letters, spaces, and dots.")
        elif not re.match(phone_pattern, phone):
            messages.error(request, "Invalid phone number. Please provide a 10-digit number.")
            

        else:
            try:
                date_obj = datetime.strptime(date_of_birth, '%Y-%m-%d').date()
                today = date.today()

                if date_obj >= today:
                    messages.error(request, "Invalid date of birth. Please use a past date.")
                else:
                    userdetails.fullname = fullname
                    userdetails.date_of_birth = date_obj
                    userdetails.save()
                    user_profile_instance.phone = phone
                    user_profile_instance.save()
                    return redirect('userprofile:user-profile')

            except ValueError:
                print("Invalid date format. Please use 'YYYY-MM-DD' format.")

    context = {
        'user': request.user,
        'userdetails': userdetails,
    }
    return render(request, 'userprofile/edit_profile.html', context)    


@login_required
@cache_control(no_cache=True,must_revalidate=True,no_store=True)
def change_password(request):
    if request.method == "POST":
        current_password = request.POST['password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['new_password2']

        user = request.user  

        if user.check_password(current_password):
            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                update_session_auth_hash(request, user)  # Update the session to keep the user logged in
                messages.success(request, "Password changed successfully.")
                return redirect('userprofile:user-profile')
            else:
                messages.error(request, "New password and confirmation do not match.")
        else:
            messages.error(request, "Current password is incorrect.")

    return render(request, 'userprofile/change_password.html')



@login_required
@cache_control(no_cache=True,must_revalidate=True,no_store=True)
def user_orders(request):
    # Query the orders for the logged-in user
    if request.user.is_authenticated and  not request.user.is_superuser :
    
        selected_menu = 'orders'
        orderroducts = OrderProduct.objects.filter(user=request.user).order_by('-created_at')
        orders = Order.objects.filter(user=request.user).exclude(status="New").order_by('-created_at')



        return render(request, 'userprofile/user_orders.html', {'orders': orders, 'orderproducts':orderroducts, 'selected_menu': selected_menu,})
    else:
        return redirect('landing')



@login_required
@cache_control(no_cache=True,must_revalidate=True,no_store=True)
def user_address(request):
    
    selected_menu = 'address'
    addressess  = AddressBook.objects.filter(user=request.user)

    return render(request,'userprofile/user_address.html', {'addressess' : addressess, 'selected_menu': selected_menu,})


@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def edit_address(request, address_id):
    address = get_object_or_404(AddressBook, id=address_id, user=request.user)

    if request.method == 'POST':
        # Retrieve updated data from the POST request
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        address_line_1 = request.POST.get('address_line_1')
        address_line_2 = request.POST.get('address_line_2')
        city = request.POST.get('city')
        state = request.POST.get('state')
        country = request.POST.get('country')
        pincode = request.POST.get('pincode')

        # Update the address fields
        address.name = name
        address.phone = phone
        address.address_line_1 = address_line_1
        address.address_line_2 = address_line_2
        address.city = city
        address.state = state
        address.country = country
        address.pincode = pincode

        # Save the updated address
        address.save()

        return redirect('userprofile:user-address')
    context = {
        'address': address,
    }

    return render(request, 'userprofile/edit_address.html', context)

@login_required
def user_add_address(request):
    if request.method == "POST":
        form = addressbook_form(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            return redirect('userprofile:user-address')
        else:
            print(form.non_field_errors())
    return render(request, 'userprofile/user_add_address.html')

wallet/views.py
from django.shortcuts import render
from razorpay import Order
from carts.models import CartItem
from django.contrib.auth.decorators import login_required
from wallet.models import Wallet
from django.http import JsonResponse 
from django.views.decorators.cache import cache_control
# Create your views here.

@login_required
@cache_control(no_cache=True,must_revalidate=True,no_store=True)
def wallet(request):
  wallet,created = Wallet.objects.get_or_create(user=request.user, is_active=True)
  context = {
    'wallet': wallet
  }
  return render(request, 'userprofile/wallet.html', context)

@login_required
@cache_control(no_cache=True,must_revalidate=True,no_store=True)
def get_wallet_grand_total(request):
    print("hellooo")
    order_number = request.GET.get('order_number')
    check = request.GET.get('check')
    if check:
        
        wallet = Wallet.objects.get(user=request.user,is_active=True)
        cart_items = CartItem.objects.filter(user = request.user)
        total = 0 
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)

        if request.session['coupon']:
            coupon_discount = int(request.session['coupon'])
            total -=  coupon_discount
           

        grand_total = total
        print(grand_total)
        wallet_balance = wallet.balance  
        wallet_dis = 0
        if check=='true':  
            if wallet.balance <= grand_total  :  
                grand_total = grand_total- wallet.balance   
                wallet_dis = wallet.balance
                wallet_balance = 0
            else:
                wallet_dis = grand_total
                wallet_balance = wallet.balance - grand_total
                grand_total = 0


        
                    
            return JsonResponse({"status": "success", "grand_total":grand_total,"wallet_balance":wallet_balance, "wallet_dis":wallet_dis})
        else:
            return JsonResponse({"status": "success", "grand_total":grand_total,"wallet_balance":wallet_balance, "wallet_dis":wallet_dis})
    else:
            print("hello")
            return JsonResponse({"status": "success", "grand_total":12334,"wallet_balance":1205})

templates/userprofile/account.html
{% extends "userprofile/user_profile_base.html" %}
{% block usercontent %}
     <div class="card mb-3" style="border-radius: .5rem;">
            <div class="row g-0">
              <div class="col-md-4 gradient-custom text-center text-white"
                style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                  alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
                <h5>{{user.username}}</h5>
                <p>Customer</p>
                <i class="far fa-edit mb-5"></i>
              </div>
              <div class="col-md-8">
                <div class="card-body p-4">
                  <h6>Information</h6>
                  <hr class="mt-0 mb-4">
                  <div class="row pt-1">
                    <div class="col-6 mb-3">
                      <h6>Email</h6>
                      <p class="text-muted">{{user.email}}</p>
                    </div>
                    <div class="col-6 mb-3">
                      <h6>Phone</h6>
                      <p class="text-muted">{{user.phone}}</p>
                    </div>
                  </div>
                  <hr class="mt-0 mb-4">
                  <div class="row pt-1">
                    <div class="col-6 mb-3">
                      <h6>Full Name</h6>
                      <p class="text-muted">{{user.userdetails.fullname}}</p>
                    </div>
                    <div class="col-6 mb-3">
                      <h6>Date of Birth</h6>
                      <p class="text-muted">{{user.userdetails.date_of_birth}}</p>
                    </div>
                  </div>
                  
                  <div class="form-group">
                    <a href="{% url 'userprofile:edit-profile' %}">Edit Profile</a>
                    <span class="space">&nbsp;</span> <!-- Use a span element with some space -->
                    <a href="{% url 'userprofile:change-password' %}">Change Password</a>
                </div>

                 

                 
                </div>
              </div>
            </div>
         </div>
          
     </div>
        


     {% endblock usercontent %}

templates/userprofile/change_password.html
{% extends "base.html" %}
{% block title %} Login page {% endblock title %}
{% block content %}


<div class="container">
    <div class="row text-center">
 
        <div class="col-lg-12  d-flex justify-content-center align-items-center" style="min-height: 50vh;">
            <div class="login_wrap widget-taber-content p-30 background-white border-radius-10 mb-md-5 mb-lg-0 mb-sm-5">
                <div class="padding_eight_all bg-white">
                    <div class="heading_s1">
                        <h3 class="mb-30">Change</h3>
                    </div>
                    <form method="post" >
                        {% csrf_token %} 
                        <div class="form-group">
                            <input type="password" required="" name="password" placeholder="Current Password">
                        </div>
                        <div class="form-group">
                            <input required="" type="password" name="new_password" placeholder="New Password">
                        </div>
                        <div class="form-group">
                            <input required="" type="password" name="new_password2" placeholder=" Confirm Password">
                        </div>                
                            
                        <div class="form-group">
                            <button type="submit" class="btn btn-fill-out btn-block hover-up" name="login">Change Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    

    </div>

</div>



{% endblock content %}

templates/userprofile/edit_address.html
{% extends "userprofile/user_profile_base.html" %}
{% block usercontent %}

<form  method="POST"> 
    {% csrf_token %}
<div class="row">
    <div class="col-md-6 form-group">
        <label>Name</label>
        <input class="form-control" type="text" name="name" value="{{ address.name }}">
    </div>
    <div class="col-md-6 form-group">
        <label>Mobile No</label>
        <input class="form-control" name="phone" type="text" value="{{ address.phone }}">
    </div>
    <div class="col-md-6 form-group">
        <label>Address Line 1</label>
        <input class="form-control" name="address_line_1" type="text" value="{{ address.address_line_1 }}">
    </div>
    <div class="col-md-6 form-group">
        <label>Address Line 2</label>
        <input class="form-control" name="address_line_2" type="text" value="{{ address.address_line_2 }}">
    </div>
    <div class="col-md-6 form-group">
        <label>Country</label>
        <input class="form-control" name="country" type="text" value="{{ address.country }}">
    </div>
    <div class="col-md-6 form-group">
        <label>City</label>
        <input class="form-control" name="city" type="text" value="{{ address.city }}">
    </div>
    <div class="col-md-6 form-group">
        <label>State</label>
        <input class="form-control" name="state" type="text" value="{{ address.state }}">
    </div>
    <div class="col-md-6 form-group">
        <label>ZIP Code</label>
        <input class="form-control" name="pincode" type="text" value="{{ address.pincode }}">
    </div>
</div>
<button type="submit" class="btn btn-primary">
    Update address
</button>

{% endblock %}

templates/userprofile/edit_profile.html
{% extends "userprofile/user_profile_base.html" %}
{% block usercontent %}
<div class="card mb-4">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
        <form method ="post">
        {% csrf_token %}
          <p class="mb-0 form-control-plaintext">Full Name</p>
        </div>
        <div class="col-sm-9">
          <input  class="text-muted form-control-plaintext" type="text" value="{{user.userdetails.fullname}}" name = 'full_name'> 
        </div>
      </div>

      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0 form-control-plaintext">Phone</p>
        </div>
        <div class="col-sm-9">
          <input class="text-muted form-control-plaintext" type="text" value="{{user.phone}}" name='phone'  >
          <p class="text-muted mb-0"></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <p class="mb-0 form-control-plaintext">DOB</p>
        </div>
        <div class="col-sm-9">
          <i></i>
          <input class="text-muted form-control-plaintext col-md-3" placeholder="sdd"  type="date" value="{{user.userdetails.date_of_birth}}" name='DOB'>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">Save Changes</button>
      

    </form>

    </div>
  </div>

{% endblock usercontent %}

templates/userprofile/user_add_address.html
{% extends "userprofile/user_profile_base.html" %}



{% block usercontent %}

<form  method="POST"> 
    {% csrf_token %}
<div class="row">
    <div class="col-md-6 form-group">
        <label>Name</label>
        <input class="form-control" type="text" name="name" placeholder="John">
    </div>
    <div class="col-md-6 form-group">
        <label>Mobile No</label>
        <input class="form-control" name="phone" type="text" placeholder="+123 456 789">
    </div>
    <div class="col-md-6 form-group">
        <label>Address Line 1</label>
        <input class="form-control" name="address_line_1" type="text" placeholder="123 Street">
    </div>
    <div class="col-md-6 form-group">
        <label>Address Line 2</label>
        <input class="form-control" name="address_line_2" type="text" placeholder="123 Street">
    </div>
    <div class="col-md-6 form-group">
        <label>Country</label>
        <input class="form-control" name="country" type="text" placeholder="India">
    </div>
    <div class="col-md-6 form-group">
        <label>City</label>
        <input class="form-control" name="city" type="text" placeholder="New York">
    </div>
    <div class="col-md-6 form-group">
        <label>State</label>
        <input class="form-control" name="state" type="text" placeholder="New York">
    </div>
    <div class="col-md-6 form-group">
        <label>ZIP Code</label>
        <input class="form-control" name="pincode" type="text" placeholder="123">
    </div>
</div>
<button type="submit" class="btn btn-primary">
    Create address
</button>
</form>
{% endblock %}

templates/userprofile/user_address.html
{% extends "userprofile/user_profile_base.html" %}



{% block usercontent %}
<div class=" mb-3 mb-lg-0">
    <a href="{% url 'userprofile:user-add-address' %}" class="btn btn-success btn-small">Add Address</a>
</div>

<div class="my-4"></div> 

<div class="row">
    {% for address in addressess   %}
    <div class="col-lg-6">
        <div class="card mb-3 mb-lg-4"> 
            <div class="card-header">
                <h5 class="mb-0">Your Address</h5>
            </div>
            <div class="card-body">
                <p class="card-text mb=0">{{address.name}}</p>
                <p class="card-text mb=0">{{address.full_address}}</p>   
                <p class="card-text mb=0">{{address.city}}, {{address.state}}</p>  
                <p class="card-text mb=0">{{address.country}}</p>
                <p class="card-text mb=0">{{address.email}}</p>
                <p class="card-text mb=0">{{address.phone}}</p>
                <p class="card-text mb=0">{{address.pincode}}</p>
                <a href= "{% url 'userprofile:edit-address' address.id %}" class="btn-small">Edit</a>
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <span class="space">&nbsp;</span> 
                <a href= "{% url 'delete_address' address.id %}" class="btn-small">Delete</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/userprofile/user_orders.html
{% extends "userprofile/user_profile_base.html" %}



{% block usercontent %}


    <div class="card">
        <div class="card-header">
            <h5 class="mb-0">Your Orders</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Order</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Total</th>
                            <th>Actions</th>
                        </tr>
                    </thead>

                    
                    {% for order in orders  %}
                    <tbody>
                        <tr>
                            <td>#{{order.order_number}}</td>
                            <td>{{order.created_at}}</td>
                            <td>{{order.status}}</td>
                            <td>{{order.order_total}}</td>
                            <td><a href="{% url 'user-order-details' order_number=order.order_number %}" class="btn-small d-block">view</a></td>
                        </tr>
                        {% endfor %}
                        

                    </tbody>
                </table>
            </div>
        </div>

</div>

{% endblock usercontent %}

templates/userprofile/user_profile_base.html
{% extends "base.html" %}
{% block title %} User Profile  {% endblock title %}
{% block content %}
<section class="pt-150 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 m-auto">
                <div class="row">
                    <div class="col-md-5">
                        
                        <div class="dashboard-menu">
                            <!-- Sidebar menu with links to profile, orders, address, etc. -->
                            <ul >   
                                <li {% if selected_menu == 'profile' %} class="selected" style="background-color: #f0f0f0; min-height: 45px; display: flex; align-items: center;" {% endif %} style="min-height: 45px; display: flex; align-items: center;"><a href="{% url 'userprofile:user-profile' %}?menu_item=profile"><i class="fi-rs-user mr-10"></i> PROFILE</a></li>


                                <li {% if selected_menu == 'orders' %} class="selected" style="background-color: #f0f0f0; min-height: 45px; display: flex; align-items: center;" {% endif %} style="min-height: 45px; display: flex; align-items: center;"><a href="{% url 'userprofile:user-orders' %}?menu_item=orders"><i class="fi-rs-shopping-bag mr-10"></i> ORDERS</a></li>


                                <li {% if selected_menu == 'address' %} class="selected" style="background-color: #f0f0f0; min-height: 45px; display: flex; align-items: center;" {% endif %} style="min-height: 45px; display: flex; align-items: center; min-height: 45px; display: flex; align-items: center;"><a href="{% url 'userprofile:user-address' %}?menu_item=address"><i class="fi-rs-marker mr-10"></i> MY ADDRESS</a></li>

                                <li  style="min-height: 45px;display: flex; align-items: center; "><a href=" {% url 'wallet' %} "><i class="fas fa-wallet mr-10"></i> WALLET </a></li>


                                <li  style="min-height: 45px;display: flex; align-items: center; "><a href="{% url 'signout' %} "><i class="fi-rs-sign-out mr-10"></i> LOG OUT</a></li>
                                <!-- Add more sections as needed -->
                            </ul>
                        </div>

                    </div>
                    <div class="col-md-6">
                        <div class="dashboard-content ">
                            <!-- This is where the dynamic content will be loaded -->
                            {% block usercontent %} {% endblock usercontent %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<!-- Preloader Start -->
<div id="preloader-active">
<div class="preloader d-flex align-items-center justify-content-center">
    <div class="preloader-inner position-relative">
        <div class="text-center">
            <h5 class="mb-5">Now Loading</h5>
            <div class="loader">
                <div class="bar bar1"></div>
                <div class="bar bar2"></div>
                <div class="bar bar3"></div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Vendor JS-->
<script src="assets/js/vendor/modernizr-3.6.0.min.js"></script>
<script src="assets/js/vendor/jquery-3.6.0.min.js"></script>
<script src="assets/js/vendor/jquery-migrate-3.3.0.min.js"></script>
<script src="assets/js/vendor/bootstrap.bundle.min.js"></script>
<script src="assets/js/plugins/slick.js"></script>
<script src="assets/js/plugins/jquery.syotimer.min.js"></script>
<script src="assets/js/plugins/wow.js"></script>
<script src="assets/js/plugins/jquery-ui.js"></script>
<script src="assets/js/plugins/perfect-scrollbar.js"></script>
<script src="assets/js/plugins/magnific-popup.js"></script>
<script src="assets/js/plugins/select2.min.js"></script>
<script src="assets/js/plugins/waypoints.js"></script>
<script src="assets/js/plugins/counterup.js"></script>
<script src="assets/js/plugins/jquery.countdown.min.js"></script>
<script src="assets/js/plugins/images-loaded.js"></script>
<script src="assets/js/plugins/isotope.js"></script>
<script src="assets/js/plugins/scrollup.js"></script>
<script src="assets/js/plugins/jquery.vticker-min.js"></script>
<script src="assets/js/plugins/jquery.theia.sticky.js"></script>
<!-- Template  JS -->
<script src="assets/js/main.js"></script>
<script src="https://kit.fontawesome.com/400fcdfbd4.js" crossorigin="anonymous"></script>
</body>


<!-- Mirrored from wp.alithemes.com/html/evara/evara-frontend/page-account.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Aug 2021 15:27:15 GMT -->
</html>

{% endblock content %}