adminside/urls.py
from django.urls import path
from . import views
app_name = 'adminside'

urlpatterns = [
    path('', views.admin_login, name="adminlogin"),
    path('admin-logout/', views.admin_logout, name="admin-logout"),
    path('dashboard/', views.dashboard, name="dashboard"), 


    path('dashboard/show-product/', views.show_product, name="show-product"),
    path('dashboard/users-list/', views.users_list, name="users-list"),
    path('admin-users-block-unblock/<int:id>',views.admin_users_block_unblock, name = "admin-users-block-unblock"),
    path('dashboard/categories', views.categories, name="categories"),
    path('dashboard/add-product', views.add_product, name="add-product"),
    path('dashboard/orders', views.admin_orders, name="admin-orders"),

    path('soft-delete-category/<int:category_id>/', views.toggle_soft_delete, name='soft-delete-category'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit-product'),
    path('update-product/<int:product_id>/', views.update_product, name='update-product'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete-product'),
    path('admin-orders-details/<int:order_number>', views.admin_orders_details, name='admin-orders-details'),
    path('delivered-order/<int:order_number>/', views.delivered_order, name='delivered-order'),
    path('adminadd-variations/', views.add_variations, name='add-variations'),
    path('adminadd-coupon/', views.add_coupon, name='add-coupon'),
    
    
    path('add-product-offer/', views.add_product_offer, name='add_product_offer'),
    path('edit-product-offer/<int:offer_id>/', views.edit_product_offer, name='edit_product_offer'),
    path('add-category-offer/',views.add_category_offer, name='add_category_offer'),
    path('category-offer-list/',views.category_offer_list, name='category_offer_list'),
    path('edit_category_offer/<int:category_offer_id>/', views.edit_category_offer, name='edit_category_offer'),
    



    
]

carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name = 'cart'),
    path('add-cart/<int:id>/', views.add_cart, name = 'add-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name = 'remove-cart'),
    path('remove-cart-item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name = 'remove-cart-item'),
    
    path('checkout/', views.checkout, name = 'checkout'), 
    path('calculate-coupon-discount/', views.calculate_coupon_discount, name='calculate_coupon_discount'),

]

orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('order-summary/', views.order_summary, name='order-summary'),
    path('place-order/', views.place_order, name='place-order'),
    path('payment/payment-success', views.payment_success, name='payment-success'),
    path('payment/payment-failed/', views.payment_failed, name='payment-failed'),
    path('payment-success-page/', views.payment_success_page, name='payment-success-page'),
    path('user-order-details/<int:order_number>', views.user_order_details, name = 'user-order-details'),
    path('order-cancel-user/<int:order_number>', views.order_cancel_user, name='order-cancel-user'),
    path('add-address/', views.add_address, name='add-address'),
    path('default_address/<int:id>', views.default_address, name="default_address"),
    path('delete_address/<int:id>', views.delete_address, name="delete_address"),
    path('sales-report', views.sales_report, name='sales-report'),


    

]

sneaker_street/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('',include('userside.urls')),
    path('adminlogin/',include('adminside.urls')),
    path('',include('userprofile.urls')),
    path('cart/',include('carts.urls')),
    path('orders/',include('orders.urls')),
    path('wallet/', include('wallet.urls')),
     path('offers/', include('offers.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/models.py
from django.utils import timezone
from django.db import models
from userside.models import *

# Create your models here.

class PaymentMethod(models.Model):
   method_name = models.CharField(max_length=50)
   is_active = models.BooleanField(default=True)
   created_at = models.DateTimeField(auto_now_add=True)

   def __str__(self):
      return self.method_name


class Payment(models.Model):
  PAYMENT_STATUS_CHOICES =(
        ("PENDING", "Pending"),
        ("FAILED", "Failed"),
        ("SUCCESS", "Success"),
      )
  user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
  payment_id = models.CharField(max_length=100)
  payment_order_id = models.CharField(max_length=100,null=True,blank=True)
  payment_method = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE)
  amount_paid = models.CharField(max_length=100)#total amount paid
  status = models.CharField(max_length=100)
  created_at = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.payment_id
    


class Coupon(models.Model):
   coupon_code = models.CharField(max_length=50, unique=True)
   discount = models.DecimalField(max_digits=10, decimal_places=0)
   valid_from = models.DateTimeField()
   valid_to = models.DateTimeField()
   active = models.BooleanField(default=True)
   minimum_amount = models.IntegerField(default=500)

   def __str__(self):
       return self.coupon_code



class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
        ('Returned', 'Returned'),
    )

    user = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.DO_NOTHING, null=True)#NEED TO REMOVE THE NULL=TRUE WHENEVER I TRUNCATE THE DATABASE
    wallet_discount = models.IntegerField(null=True, default=0)
    coupon_discount = models.IntegerField(null=True, default=0)
    order_number = models.CharField(max_length=20)
    shipping_address = models.ForeignKey(
        AddressBook, on_delete=models.SET_NULL, null=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=20, choices=STATUS, default='New')
    ip = models.CharField(max_length=20, blank=True)
    is_ordered = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'Order {self.order_number}'


class OrderProduct(models.Model):
    order =  models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation)
    color = models.CharField(max_length=50)
    size = models.CharField(max_length=50)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at =  models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now = True)




    def  __str__(self):
        return self.product.Product_name
    

orders/forms.py
from django import forms
from userside.models import AddressBook


class addressbook_form(forms.ModelForm):
    class Meta:
        model = AddressBook
        fields = '__all__'
        exclude = ['created_at', 'user',
                   'updated_at', 'is_default', 'is_active']


    

adminside/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from offers.models import CategoryOffer, ProductOffer
from userside.models import UserProfile, Product, Category, Product_image, Variation
from django.contrib.auth import authenticate,login,logout
from django.utils.text import slugify
from django.views.decorators.cache import cache_control
from django.contrib.auth.decorators import user_passes_test
from orders.models import Coupon, Order, OrderProduct, variation_category_choice
from django.utils import timezone
from django.http import HttpResponseBadRequest
# Create your views here.

def is_superuser(user):
    return user.is_superuser

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_login(request):
    if request.user.is_authenticated and request.user.is_superuser :
        return render(request, 'adminside/dashboard.html')
    else:
        if request.method == "POST":
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(request, email=email , password=password)
            if user is not None and user.is_superuser:
                login(request,user)
                return redirect('adminside:dashboard')
            else :
                messages.error(request,'Invalid credentials')
                return render(request, 'adminside/admin_login.html')      
        else:
            return render(request, 'adminside/admin_login.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@user_passes_test(is_superuser)
def dashboard(request):
    if request.user.is_authenticated:
        return render(request, 'adminside/dashboard.html')
    else:
        return redirect('adminside:admin-login')
    
  
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_logout(request):
   if request.user.is_authenticated:
        logout(request)
   return redirect('adminside:adminlogin')
    
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@user_passes_test(is_superuser)
def show_product(request):
    if request.user.is_authenticated:
        products = Product.objects.all()
        return render(request, 'adminside/show_product.html', {'products':products})
    else:
        return render(request, 'adminside/admin_login.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@user_passes_test(is_superuser)
def users_list(request):
    if request.user.is_authenticated:
        users = UserProfile.objects.all()
        return render(request,'adminside/users_list.html', {'users': users})
    else:
        return render(request, 'adminside/admin_login.html')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@user_passes_test(is_superuser)
def admin_users_block_unblock(request, id):
    if request.user.is_authenticated:
        user = UserProfile.objects.get(id = id )
        if user.is_blocked:
            user.is_blocked = False
            user.is_active = True
            user.save()
            messages.success(request, "User is Unblocked")
        else:
            user.is_active = False
            user.is_blocked = True
            user.save()
            messages.warning(request, "User is blocked")
        return redirect("adminside:users-list")
    else:
        return render(request, 'adminside/admin_login.html')
    
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@user_passes_test(is_superuser)
def categories(request):
    if request.user.is_authenticated:

        categories = Category.objects.all()

        if request.method == 'POST':
            category_name = request.POST['category_name']
            slug = slugify(category_name)
            description = request.POST['description']
            is_available = request.POST.get('is_available') == 'true'  
            soft_deleted = request.POST.get('soft_deleted', False)  
            # Check if the category name is empty or already exists
            if not category_name:
                messages.error(request, 'Category name should not be empty.')
            elif Category.objects.filter(Category_name=category_name).exists():
                messages.error(request, 'Category with this name already exists.')
            else:
                # Handle category image upload
                category_image = request.FILES.get('category_image')
                
                
                # Create and save the category
                category = Category(
                    Category_name=category_name,
                    slug=slug,
                    description=description,
                    is_available=is_available,
                    soft_deleted=soft_deleted,
                    Category_image=category_image  # Assign the uploaded image
                )
                category.save()
                messages.success(request, 'Category added successfully!')
                return redirect("adminside:categories")  # Redirect to the category list view

        return render(request, 'adminside/categories.html', {"categories" : categories})
    else:
        return render(request, 'adminside/admin_login.html')



def toggle_soft_delete(request, category_id):
    if request.user.is_authenticated:
        category = get_object_or_404(Category, pk=category_id)
        category.soft_deleted = not category.soft_deleted  # Toggle the soft_deleted field
        category.save()
        
        return redirect('adminside:categories')



@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@user_passes_test(is_superuser)
def add_product(request):
    if request.user.is_authenticated:
        categories = Category.objects.all()
        products = Product.objects.all()
        
        if request.method == "POST":
            product_name = request.POST['product_name']

            try:
                price = float(request.POST['price'])
                max_price = float(request.POST['max_price'])
                quantity = int(request.POST['quantity'])

                if price < 0 or max_price < 0 or quantity < 0:
                    messages.error(request, 'Price, max price, and quantity must be non-negative.')
                else:
                    if Product.objects.filter(Product_name=product_name).exists():
                        messages.error(request, 'A product with this name already exists.')
                        
                    slug = slugify(product_name)
                    category_id = request.POST['category']
                    category = Category.objects.get(id=category_id)
                    brand = request.POST['brand']
                    description = request.POST['description']
                    price = request.POST['price']
                    main_image = request.FILES.get('main_image')
                    additional_images = request.FILES.getlist('additional_images')
                    max_price = request.POST['max_price']
                    quantity = request.POST['quantity']
                    is_available = request.POST.get('is_available') 
                    if main_image == None:
                        messages.warning(request, "Upload a main img")
                        return redirect('adminside:add-product')
                    if len(additional_images) != 4 or any(image is None for image in additional_images):
                         messages.error(request, 'You must provide exactly 4 additional images, and none of them should be empty.')
                         return redirect('adminside:add-product')
                    if is_available == 'on' or is_available == 'True':
                        is_available = True
                    else:
                        is_available = False
                    soft_deleted = request.POST.get('is_available', False) 
                    if soft_deleted == 'on':
                        soft_deleted = True
                    else:
                        soft_deleted = False

                        product = Product(
                            Product_name = product_name,
                            slug = slug,
                            category = category, 
                            brand = brand, 
                            description = description,
                            price =  price,
                            main_image = main_image,
                            max_price = max_price,
                            quantity = quantity,
                            is_available = is_available,
                            soft_deleted = soft_deleted
                            )
                        # product.save()

                        product_image = Product_image()

                        for i, image in enumerate(additional_images[:4]):
                            

                            if i == 0:
                                product_image.image2 = image
                            elif i == 1:
                                product_image.image3 = image
                            elif i == 2:
                                product_image.image4 = image
                            elif i == 3:
                                product_image.image5 = image
                                
                            
                        # product_image.image2 = image2
                        # product_image.image3 = image3
                        # product_image.image4 = image4
                        # product_image.image5 = image5

                        product.save()
                        product_image.product = product
                        product_image.save()
                        return redirect('adminside:show-product') 

            except ValueError:
                messages.error(request, 'Invalid price, max price, or quantity.')      

             

templates/adminside/base1.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">


<!-- Mirrored from wp.alithemes.com/html/evara/evara-backend/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Aug 2021 15:32:35 GMT -->
<head>
    <meta charset="utf-8">
    <title>{% block title %} {%endblock title%}</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href= {% static "assets-1/imgs/theme/favicon.svg" %} >
    <!-- Template CSS -->
    <link href={% static "assets-1/css/main.css"%} rel="stylesheet" type="text/css" />
</head>

<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="screen-overlay"></div>
    <aside class="navbar-aside" id="offcanvas_aside">
        <div class="aside-top">
            <a href="index.html" class="brand-wrap">
                <img src  = "{% static 'assets-1/imgs/theme/logo.svg' %}" class="logo" alt="Evara Dashboard">
            </a>
            <div>
                <button class="btn btn-icon btn-aside-minimize"> <i class="text-muted material-icons md-menu_open"></i> </button>
            </div>
        </div>
        <nav>
            <ul class="menu-aside">
                <li class="menu-item active">
                    <a class="menu-link" href="{%url 'adminside:dashboard' %}"> <i class="icon material-icons md-home"></i>
                        <span class="text">Dashboard</span>
                    </a>
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="page-products-list.html"> <i class="icon material-icons md-shopping_bag"></i>
                        <span class="text">Products</span>
                    </a>
                    <div class="submenu">
                        <a href="{%url 'adminside:show-product' %}">Product List </a>
                        <a href="{%url 'adminside:categories' %}">Categories</a>
                        <a href="{%url 'adminside:category_offer_list' %}">Category Offer</a>
                    </div>
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="page-orders-1.html"> <i class="icon material-icons md-shopping_cart"></i>
                        <span class="text">Orders</span>
                    </a>
                    <div class="submenu">
                        <a href="{%url 'adminside:admin-orders' %}">Order list 1</a>
                       
                    </div>
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="page-sellers-cards.html"> <i class="icon material-icons md-person"></i>
                        <span class="text">Users</span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'adminside:users-list' %}">Users list</a>
                        
                    </div>
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="page-form-product-1.html"> <i class="icon material-icons md-add_box"></i>
                        <span class="text">Add </span>
                    </a>
                    <div class="submenu">
                        <a href="{% url 'adminside:add-product' %}">Add product </a>
                        <a href="{% url 'adminside:add-variations' %}">Add Variations</a>
                        <a href="{% url 'adminside:add-coupon' %}">Add Coupon</a>
                        <a href="{% url 'adminside:add_product_offer' %}">Add Product offer</a>
                        <a href="{% url 'adminside:add_category_offer' %}">Add Category offer</a>

                    </div>
                   
                </li>
                {% comment %} <li class="menu-item has-submenu">
                    <a class="menu-link" href="page-transactions-1.html"> <i class="icon material-icons md-monetization_on"></i>
                        <span class="text">Transactions</span>
                    </a>
                    <div class="submenu">
                        <a href="page-transactions-1.html">Transaction 1</a>
                        <a href="page-transactions-2.html">Transaction 2</a>
                    </div>
                </li>
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="#"> <i class="icon material-icons md-person"></i>
                        <span class="text">Account</span>
                    </a>
                    <div class="submenu">
                        <a href="page-account-login.html">User login</a>
                        <a href="page-account-register.html">User registration</a>
                        <a href="page-error-404.html">Error 404</a>
                    </div>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="page-reviews.html"> <i class="icon material-icons md-comment"></i>
                        <span class="text">Reviews</span>
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="page-brands.html"> <i class="icon material-icons md-stars"></i>
                        <span class="text">Brands</span> </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" disabled href="#"> <i class="icon material-icons md-pie_chart"></i>
                        <span class="text">Statistics</span>
                    </a>
                </li>
            </ul>
            <hr>
            <ul class="menu-aside">
                <li class="menu-item has-submenu">
                    <a class="menu-link" href="#"> <i class="icon material-icons md-settings"></i>
                        <span class="text">Settings</span>
                    </a>
                    <div class="submenu">
                        <a href="page-settings-1.html">Setting sample 1</a>
                        <a href="page-settings-2.html">Setting sample 2</a>
                    </div>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="page-blank.html"> <i class="icon material-icons md-local_offer"></i>
                        <span class="text"> Starter page </span>
                    </a>
                </li> {% endcomment %}
            </ul>
            <br>
            <br>
        </nav>
    </aside>
    <main class="main-wrap">
        <header class="main-header navbar">
            <div class="col-search">
                <form class="searchform">
                    <div class="input-group">
                        <input list="search_terms" type="text" class="form-control" placeholder="Search term">
                        <button class="btn btn-light bg" type="button"> <i class="material-icons md-search"></i></button>
                    </div>
                    <datalist id="search_terms">
                        <option value="Products">
                        <option value="New orders">
                        <option value="Apple iphone">
                        <option value="Ahmed Hassan">
                    </datalist>
                </form>
            </div>
            <div class="col-nav">
                <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"> <i class="material-icons md-apps"></i> </button>
                <ul class="nav">
                    {% comment %} <li class="nav-item">
                        <a class="nav-link btn-icon" href="#">
                            <i class="material-icons md-notifications animation-shake"></i>
                            <span class="badge rounded-pill">3</span>
                        </a>
                    </li> {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link btn-icon darkmode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
                    </li>
                    <li >
                        <a href="{% url 'adminside:admin-logout'  %}" class="btn btn-sm font-sm btn-light rounded">
                            logout
                        </a>
                        
                    </li>
                    <li class="dropdown nav-item">
                        <a class="" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src={% static "assets-1/imgs/people/avatar2.jpg" %} alt="User"></a>
                        {% comment %} <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                            <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                            <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item text-danger" href="#"><i class="material-icons md-exit_to_app"></i>Logout</a>
                        </div> {% endcomment %}
                    </li>
                </ul>
            </div>
        </header>
        
        {% block content %} {%endblock content%}
        

        <footer class="main-footer font-xs">
            <div class="row pb-30 pt-15">
                <div class="col-sm-6">
                    <script>
                    document.write(new Date().getFullYear())
                    </script> ©, Evara - HTML Ecommerce Template .
                </div>
                <div class="col-sm-6">
                    <div class="text-sm-end">
                        All rights reserved
                    </div>
                </div>
            </div>
        </footer>
    </main>
    <script src={% static "assets-1/js/vendors/jquery-3.6.0.min.js" %}></script>
    <script src={% static "assets-1/js/vendors/bootstrap.bundle.min.js" %}></script>
    <script src={% static "assets-1/js/vendors/select2.min.js" %}></script>
    <script src={% static "assets-1/js/vendors/perfect-scrollbar.js" %}></script>
    <script src={% static "assets-1/js/vendors/jquery.fullscreen.min.js" %}></script>
    <script src={% static "assets-1/js/vendors/chart.js" %}></script>
    <!-- Main Script -->
    <script src={% static "assets-1/js/main.js" type="text/javascript" %}></script>
    <script src={% static "assets-1/js/custom-chart.js" type="text/javascript" %}></script>
</body>


<!-- Mirrored from wp.alithemes.com/html/evara/evara-backend/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Aug 2021 15:32:57 GMT -->
</html>