carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name = 'cart'),
    path('add-cart/<int:id>/', views.add_cart, name = 'add-cart'),
    path('remove-cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name = 'remove-cart'),
    path('remove-cart-item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name = 'remove-cart-item'),
    
    path('checkout/', views.checkout, name = 'checkout'), 
    path('calculate-coupon-discount/', views.calculate_coupon_discount, name='calculate_coupon_discount'),

]

offers/urls.py
from django.urls import path
from . import views

app_name = 'offers'

urlpatterns = [

  path('offers', views.offers, name='offers'),
  path('category-offer-product/<slug:offer_slug>', views.category_offer_product, name='category-offer-product'),
  path('product-offer-product/<slug:offer_slug>', views.product_offer_product, name='product-offer-product'),
]

sneaker_street/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('',include('userside.urls')),
    path('adminlogin/',include('adminside.urls')),
    path('',include('userprofile.urls')),
    path('cart/',include('carts.urls')),
    path('orders/',include('orders.urls')),
    path('wallet/', include('wallet.urls')),
     path('offers/', include('offers.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

offers/models.py
 
from django.db import models
from userside.models import Product,Category
from django.utils.text import slugify

class ProductOffer(models.Model):
  offer_name = models.CharField(max_length=100)
  expire_date = models.DateField()
  product = models.ManyToManyField(Product)
  discount_percentage = models.IntegerField(default=0)
  product_offer_slug = models.SlugField(blank=True, max_length=200,unique=True)
  product_offer_image = models.ImageField(upload_to='photos/offerimages', null=True)
  is_active = models.BooleanField(default=True)

  def save(self, *args, **kwargs):
    if int(self.discount_percentage) > 100:
      self.discount_percentage = 100

    counter = ProductOffer.objects.filter(product_offer_slug__istartswith=self.product_offer_slug).count()  
    if counter > 0:
      self.product_offer_slug = slugify(f'{self.offer_name}-{counter}')
    else:
      self.product_offer_slug = slugify(self.offer_name)

    super( ProductOffer, self).save(*args, **kwargs)  

  def __str__(self):
    return self.offer_name 
  

class CategoryOffer(models.Model):
    offer_name = models.CharField(max_length=100)
    expire_date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    discount_percentage = models.IntegerField(default=0)
    category_offer_slug = models.SlugField(blank=True, max_length=200,unique=True)
    category_offer_image = models.ImageField(upload_to='photos/offerimages', null=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if int(self.discount_percentage) > int(100):
            self.discount_percentage = 100

        counter = CategoryOffer.objects.filter(category_offer_slug__istartswith=self.category_offer_slug).count()  
        if counter > 0:
            self.category_offer_slug = slugify(f'{self.offer_name}-{counter}')
        else:
            self.category_offer_slug = slugify(self.offer_name)

        super(CategoryOffer, self).save(*args, **kwargs)    

    def __str__(self):
        return self.offer_name

offers/views.py
from django.shortcuts import redirect, render
from django.views.decorators.cache import cache_control
from offers.models import CategoryOffer, ProductOffer
from userside.models import Category, Product
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
# Create your views here.


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def offers(request):
  category_offer = CategoryOffer.objects.all()
  product_offer = ProductOffer.objects.all()
  context = {
    'category_offer':category_offer,
    'product_offer' :product_offer
  }
  return render(request, 'offers.html', context)


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def category_offer_product(request, offer_slug, category=None):

  try:
    category_offer = get_object_or_404(CategoryOffer, category_offer_slug=offer_slug)
  except:
    return redirect('shop-product')

  category = category_offer.category

  if category:
    # category = category_offer.category.filter(is_available=True, slug = category)
    products = Product.objects.filter(category=category)
    paginator=Paginator(products,3)
    page=request.GET.get('page')
    paged_products=paginator.get_page(page)
    product_count=products.count()
    categories=[category]
    context={
          'products':paged_products,
          'product_count':product_count,
          'categories':categories,

      }
    return render(request, 'page-shop.html',context)
  else:
      products = Product.objects.filter(category=category)
      paginator=Paginator(products,3)
      page=request.GET.get('page')
      paged_products=paginator.get_page(page)
      product_count=products.count()
      categories=[category]

      context={
            'products':paged_products,
            'product_count':product_count,
            'categories':categories,

        }
      return render(request, 'page-shop.html',context)
  

  
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def product_offer_product(request, offer_slug):
  try:
    product_offer = get_object_or_404(ProductOffer, product_offer_slug=offer_slug)
  except:
    return redirect('shop-product')
  
  products = product_offer.product.filter(is_available=True)
  paginator=Paginator(products,3)
  page=request.GET.get('page')
  paged_products=paginator.get_page(page)
  product_count=products.count()
  categories = Category.objects.all()

  context = {
    'products':paged_products,
    'product_count':product_count,
    'categories':categories,

  }
  return render(request, 'page-shop.html',context)

templates/forgotpassword.html
{% extends "base.html" %}
{% block title %} Login page {% endblock title %}
{% block content %}


<div class="container">

    <div class="row text-center">
        
 
        <div class="col-lg-12  d-flex justify-content-center align-items-center" style="min-height: 50vh;">
            <div class="login_wrap widget-taber-content p-30 background-white border-radius-10 mb-md-5 mb-lg-0 mb-sm-5">
                <div class="padding_eight_all bg-white">
                    <div class="heading_s1">
                        <h3 class="mb-30">Enter Your Email</h3>
                    </div>
                    <form method="post" action="{% url 'forgotPassword' %}" >
                        {% csrf_token %} 
                        <div class="form-group">
                            <input type="email" required="" name="email" placeholder="Your Email">
                        </div>
                        
                        <div>
                                <a class="text-muted" href="{% url 'user_login' %}">Got Password? Login</a>
                        </div>
                        
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                        <div class="form-group">
                            <button type="submit" class="btn btn-fill-out btn-block hover-up" name="login">Send OTP</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    

    </div>

</div>

<script>
    // Function to check if OTP has expired
    function checkOTPExpiry() {
        var otpExpired = {{ otp_expired|default:"False"|lower }};
        if (otpExpired === "true") {
            // OTP has expired, refresh the page
            location.reload();
        }
    }

    // Call the function every few seconds (e.g., every 5 seconds)
    setInterval(checkOTPExpiry, 5000);  // 5000 milliseconds = 5 seconds
</script>



{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% block title %} Login page {% endblock title %}
{% block content %}


<div class="container">
    <div class="row text-center">
 
        <div class="col-lg-12  d-flex justify-content-center align-items-center" style="min-height: 50vh;">
            <div class="login_wrap widget-taber-content p-30 background-white border-radius-10 mb-md-5 mb-lg-0 mb-sm-5">
                <div class="padding_eight_all bg-white">
                    <div class="heading_s1">
                        <h3 class="mb-30">Login</h3>
                    </div>
                    <form method="post" >
                        {% csrf_token %} 
                        <div class="form-group">
                            <input type="email" required="" name="email" placeholder="Your Email">
                        </div>
                        <div class="form-group">
                            <input required="" type="password" name="password" placeholder="Password">
                        </div>
                        
                        <div>
                                <a class="text-muted" href="#">Forgot password?</a>
                        </div>
                            
                            

                        <div class="form-group">
                            <button type="submit" class="btn btn-fill-out btn-block hover-up" name="login">Log in</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    

    </div>

</div>



{% endblock content %}

templates/offers.html
{% extends "base.html" %}
{% load static %}
{% block title %} Offers {% endblock title %}
{% block content %}


<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow">Home</a>
                <span></span> Offers
            </div>
        </div>
    </div>
    <section class="mt-50 mb-50">
        <div class="container custom">
            <div class="row">
                <div class="col-lg-12">
                    <div class="single-header mb-50 text-center">
                        <h1 class="font-xxl text-brand"> Our Offers</h1>
                        <div class="entry-meta meta-1 font-xs mt-15 mb-15">
                            <span class="post-by">32 Sub Categories</span>
                            <span class="post-on has-dot">1020k Article</span>
                            <span class="time-reading has-dot">480 Authors</span>
                            <span class="hit-count  has-dot">29M Views</span>
                        </div>
                    </div>
                    <div class="p-4 bg-secondary border">
                        <h3>Category Offers</h3>
                    </div>
                    
                    <div  style="margin-top:20px;"></div>

                    
                    <div class="loop-grid pr-30">
                        <div class="row">
                            {% for cat in category_offer %}
                            <div class="col-lg-4">
                                <article class="wow fadeIn animated hover-up mb-30">
                                    <div class="post-thumb img-hover-scale">
                                        <a href="blog-post-right.html">
                                            <img src="{{cat.category_offer_image.url}}" alt="">
                                        </a>
                                        <div class="entry-meta">
                                            <a class="entry-meta meta-2" href="blog-category-grid.html">Sport</a>
                                        </div>
                                    </div>
                                    <div class="entry-content-2">
                                        <h3 class="post-title mb-15">
                                            <a href="">{{cat.offer_name}}</a></h3>
                                        <h4>Applicable Categories</h4>    
                                        <p class="post-exerpt mb-30">{{cat.category}}</p>
                                        <div class="entry-meta meta-1 font-xs color-grey mt-10 pb-10">
                                            <div>
                                                <span class="post-on"> <i class="fi-rs-clock"></i> 25 April 2021</span>
                                            </div>
                                            <a class="btn btn-dark" href="{% url 'offers:category-offer-product' cat.category_offer_slug %}">View Products</a>
                                        </div>
                                    </div>
                                </article>
                            </div>
                            {% endfor %}
                            
                        </div>
                    </div>

                    <div class="p-4 bg-secondary border">
                        <h3>Product Offers</h3>
                    </div>
                    <div  style="margin-top:20px;"></div>
                    <div class="loop-grid pr-30">
                        <div class="row">
                            {% for product in product_offer %}
                            <div class="col-lg-4">
                                <article class="wow fadeIn animated hover-up mb-30">
                                    <div class="post-thumb img-hover-scale">
                                        <a href="blog-post-right.html">
                                            <img src="{{product.product_offer_image.url}}" alt="">
                                        </a>
                                        <div class="entry-meta">
                                            <a class="entry-meta meta-2" href="blog-category-grid.html">Sport</a>
                                        </div>
                                    </div>
                                    <div class="entry-content-2">
                                        <h3 class="post-title mb-15">
                                            <a href="blog-post-right.html">{{product.offer_name}}</a></h3>
                                        <h4>Offer for Every Products</h4>     
                                        <p class="post-exerpt mb-30">{{product.products}}</p>
                                        <div class="entry-meta meta-1 font-xs color-grey mt-10 pb-10">
                                            <div>
                                                <span class="post-on"> <i class="fi-rs-clock"></i> 25 April 2021</span>
                                            </div>
                                            <a class="btn btn-dark" href="{% url 'offers:product-offer-product' product.product_offer_slug %}">View Products</a>
                                        </div>
                                    </div>
                                </article>
                            </div>
                            {% endfor %} 
                        </div>
                    </div>

                    <!--post-grid-->
                    <div class="pagination-area mt-15 mb-lg-0">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                <li class="page-item active"><a class="page-link" href="#">01</a></li>
                                <li class="page-item"><a class="page-link" href="#">02</a></li>
                                <li class="page-item"><a class="page-link" href="#">03</a></li>
                                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                <li class="page-item"><a class="page-link" href="#">16</a></li>
                                <li class="page-item"><a class="page-link" href="#"><i class="fi-rs-angle-double-small-right"></i></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
<style>
    .entry-content-2 {
        background-color: #EADBC8; /* Replace with your desired background color */
        color: #333; /* Replace with your desired text color */
        /* Add any other styles you want for this section */
    }
    
</style>
{% endblock %}

templates/otp.html
{% extends "base.html" %}
{% block title %} Login page {% endblock title %}
{% block content %}

<div class="container">
    <div class="row text-center">
 
        <div class="col-lg-12  d-flex justify-content-center align-items-center" style="min-height: 50vh;">
            <div class="login_wrap widget-taber-content p-30 background-white border-radius-10 mb-md-5 mb-lg-0 mb-sm-5">
                <div class="padding_eight_all bg-white">
                    <div class="heading_s1">
                        <h3 class="mb-30">Verification</h3>
                    </div>
                    <form method="post" >
                        {% csrf_token %} 
                        <div class="form-group">
                            <label for="otp">Enter OTP:</label>
                            <input type="text" name="otp" required>
                        </div>
                            
                            
                        <div id="otp-timer">Time remaining: 2:00</div>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="form-group">
                            
                            <button type="submit" class="btn btn-fill-out btn-block hover-up" name="login">Verify OTP </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    

    </div>

</div>
<script>

    setTimeout(function(){
        window.location.reload(1);
     }, 125000);

    function startTimer(duration, display) {
        let timer = duration, minutes, seconds;
        setInterval(function () {
            minutes = parseInt(timer / 60, 10);
            seconds = parseInt(timer % 60, 10);
    
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;
    
            display.textContent = "Time remaining: " + minutes + ":" + seconds;
    
            if (--timer < 0) {
                // Timer has expired, you can trigger OTP resend here or disable the form
                display.textContent = "OTP Expired";
                // Optionally, handle OTP expiration and resend here
            }
        }, 1000);
    }
    
    window.onload = function () {
        const otpTimerDisplay = document.querySelector('#otp-timer');
        const duration = 120; // Duration in seconds (2 minutes)
        startTimer(duration, otpTimerDisplay);
    };
    </script>

    <script>
        // Function to check if OTP has expired
        function checkOTPExpiry() {
            var otpExpired = {{ otp_expired|default:"False"|lower }};
            if (otpExpired === "true") {
                // OTP has expired, refresh the page
                location.reload();
            }
        }
    
        // Call the function every few seconds (e.g., every 5 seconds)
        setInterval(checkOTPExpiry, 5000);  // 5000 milliseconds = 5 seconds
    </script>

{% endblock content %}

templates/page-shop.html
{% extends "base.html" %}
{% block title %} Product Details {% endblock title %}
{% block content %}

<body>

    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
      <strong></strong>{{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
     {% endfor %}
     
    <!-- Quick view -->
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    {% if 'search' in request.path %}
                        <a href="index.html" rel="nofollow">Home</a>
                        <span></span> Search Result
                    {% else %}
                        <a href="index.html" rel="nofollow">Home</a>
                        <span></span> Shop
                    {% endif %}
                </div>
            </div>
        </div>
        <section class="mt-50 mb-50">
            <div class="container">
                <div class="row flex-row-reverse">
                    <div class="col-lg-9">
                        <div class="shop-product-fillter">
                            <div class="totall-product">
                                <p> We found <strong class="text-brand">{{product_count}}</strong> items for you!</p>
                            </div>
                            <div class="sort-by-product-area">
                                
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                             <li><a  href="{% url 'shop-product' att='id'%}">Default</a></li>
                                            <li><a href="{% url 'shop-product' att='price'%}">Price: Low to High</a></li>
                                            <li><a href="{% url 'shop-product' att='-price' %}">Price: High to Low</a></li>
                                        </ul> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row product-grid-3">
                         {% if products %}
                            {% for product in products %}
                            {% if not product.soft_deleted %}
                            <div class="col-lg-4 col-md-4 col-12 col-sm-6">
                                <div class="product-cart-wrap mb-30">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img product-img-zoom">
                                            <a href="{% url 'product_details' product_id=product.id %}">
                                                <img class="default-img" src="{{product.main_image.url}}" alt="">
                                                <img class="hover-img" src="{{product.product_image.image2.url}}" alt="">
                                            </a>
                                        </div>
                                        <div class="product-action-1">
                                            <a aria-label="Quick view" class="action-btn hover-up" data-bs-toggle="modal" data-bs-target="#quickViewModal">
<i class="fi-rs-search"></i></a>
                                            {% comment %} <a aria-label="Add To Wishlist" class="action-btn hover-up" href="{% url 'add_to_wishlist' id=product.id %}"><i class="fi-rs-heart"></i></a> {% endcomment %}
                                            <a aria-label="Compare" class="action-btn hover-up" href="shop-compare.html"><i class="fi-rs-shuffle"></i></a>
                                        </div>
                                        <div class="product-badges product-badges-position product-badges-mrg">
                                            {% if product.offer_percentage > 0 %}
                                            <span class="hot">{{ product.offer_percentage }}%</span>
                                            {% else %}
                                            <span class="hot">New</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="product-content-wrap">
                                        <div class="product-category">
                                            <a href="shop-grid-right.html">{{product.category}}</a>
                                        </div>
                                        <h2><a href="shop-product-right.html">{{product.Product_name}}</a></h2>
                                        <div class="rating-result" title="90%">
                                            <span>
                                                <span>90%</span>
                                            </span>
                                        </div>
                                        <div class="product-price">
                                            <span>Rs:{{product.product_price}}</span>
                                            <span class="old-price">{{product.max_price}}</span>
                                        </div>
                                        <div class="product-action-1 show">
                                            <a aria-label="Add To Cart" class="action-btn hover-up" href="{% url 'add-cart' id=product.id %}"><i class="fi-rs-shopping-bag-add"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                         {% else %}
                          <div>
                            <h2>No Result found!Please Try Again...</h2>
                          </div>
                         {% endif %}
                        </div>
                        <!--pagination-->
                        <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                            <nav aria-label="Page navigation example">
                                {% if products.has_other_pages %}
                                    <ul class="pagination justify-content-start">
                                        {% for i in products.paginator.page_range %}
                                           {% if products.number == i %}
                                             <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
                                           {% else %}
                                             <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                           {% endif %}   
                                        {% endfor %}

                                        {% if products.has_next %}
                                            <li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}"><i class="fi-rs-angle-double-small-right"></i></a></li>
                                        {% else %}
                                            <li class="page-item disabled"><a class="page-link" href="#"><i class="fi-rs-angle-double-small-right"></i></a></li>   
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </nav>
                        </div>
                    </div>
                    <div class="col-lg-3 primary-sidebar sticky-sidebar">
                        <div class="widget-category mb-30">
                            <h5 class="section-title style-1 mb-30 wow fadeIn animated">Category</h5>
                            <ul class="categories">
                                <li><a href="{% url 'shop-product-by-category' category_slug='none' %}">All products</a></li>
                            </ul>

                            {% for cat in categories %}
                            <ul class="categories">
                                <li><a href="{% url 'shop-product-by-category' category_slug=cat.slug %}">{{cat.Category_name}}</a></li>
                            </ul>
                            {% endfor %}

                            
                </div>
                <div class="sidebar-widget price_range range mb-30">
                    <div class="widget-header position-relative mb-20 pb-10">
                        <h5 class="widget-title mb-10">FILTER</h5>
                        <div class="bt-1 border-color-1"></div>
                    </div>
                    <form method="get" action="{% url 'shop-product' %}">
                    <div>
                        <label for="color">Color:</label>
                        <input type="text" name="color" >
                       
                    </div>
                       
                    <div style="margin-top:40px; margin-bottom:40px">
                        <label for="size">Size:</label>
                        <select name="size" id="size">
                            <option value="">All</option>
                            <option value="small">Small</option>
                            <option value="medium">Medium</option>
                            <option value="large">Large</option>
                            <option value="xlarge">XLarge</option>
                            <!-- Add more size options as needed -->
                        </select>
                    </div>
                        
                    
                        <input type="submit" value="Filter">
                    </form>
                    
                </div>
            </div>
        </section>
    </main>
    {% endblock content %}